### ISSUE TITLE
Any integration with a CuckooBox?

### ISSUE THREAD

**Issue by makakin** [MISP/mail_to_misp#18]
Any integration with a CuckooBox for the mail_to_misp x MISP x Cuckoo. 
For example, when mail_to_misp detected an attachment, send it to CuckooBox to analysis, then CuckooBox's result as an enrichment for the event in MISP.

**Comment by rommelfs** [comment]
This is not planned and it would be a hassle to implement it. Sending the attachment to cuckoo and waiting for the result and then feeding it into MISP is not in the design of mail_to_misp.

What we could do is adding a tag to the event so that your event is fetched by your external automation tools (when this tag is present), which then sends the attachment to Cuckoo) and removes the tag when finished.

Cuckoo-modified (https://github.com/spender-sandbox/cuckoo-modified) is acting as an interface to MISP. 

For the moment, I suggest you send your attachments to a mail_to_cuckoo handler to get this implemented the fastest.

Does that make sense to you?

**Comment by makakin** [comment]
Yes, that is a good idea!
Thank you for your recommendation!!!

**Comment by rommelfs** [comment]
Not sure, to my knowledge cuckoo-modified is the one supporting MISP out of the box.
Maybe you also want to look here: https://blog.rootshell.be/2017/01/25/quick-integration-misp-cuckoo/
